<?php echo $this->getFormInitScripts(); ?>
    <script type="text/javascript">
        window.onunload = eventClose;

        function eventClose() {
           this.parent.location.reload();
        }
    </script>
    <div class="content-header">
        <?php echo $this->getHeaderHtml(); ?>
        <p class="form-buttons"><?php echo $this->getButtonsHtml('header'); ?></p>
    </div>
<?php echo $this->getFormHtml(); ?>
<?php if ($this->hasFooterButtons()): ?>
    <div class="content-footer">
        <p class="form-buttons"><?php echo $this->getButtonsHtml('footer'); ?></p>
    </div>
<?php endif; ?>
<?php echo $this->getFormScripts(); ?>