<?php echo $this->getFormInitScripts(); ?>
    <script type="text/javascript">
        function openMyPopup() {

            var url = '<?php echo Mage::helper("adminhtml")->getUrl("bikeexchange/adminhtml_index/popup/"); ?>';
            if ($('browser_window') && typeof(Windows) != 'undefined') {
                Windows.focus('browser_window');
                return;
            }
            var dialogWindow = Dialog.info(null,{
                closable: true,
                resizable: false,
                draggable: true,
                className: 'magento',
                windowClassName: 'popup-window',
                title: 'Add New Product to BikeExchange',
                top: 50,
                width: 1200,
                height: 700,
                zIndex: 1000,
                recenterAuto: false,
                hideEffect: Element.hide,
                showEffect: Element.show,
                id: 'browser_window',
                url: url,
            });

        }


    </script>
    <div class="content-header">
        <?php echo $this->getHeaderHtml(); ?>
        <p class="form-buttons"><?php echo $this->getButtonsHtml('header'); ?></p>
    </div>
<?php echo $this->getFormHtml(); ?>
<?php if ($this->hasFooterButtons()): ?>
    <div class="content-footer">
        <p class="form-buttons"><?php echo $this->getButtonsHtml('footer'); ?></p>
    </div>
<?php endif; ?>
<?php echo $this->getFormScripts(); ?>