<div class="onestepcheckout-payment-methods">
    <?php if (count($this->getMethods()) == '1' && Mage::getStoreConfig('onestepcheckout/general/hide_payment_method')): ?>
        <dl id="checkout-payment-method-load" style="display: none">
            <?php foreach ($this->getMethods() as $_method): $_code = $_method->getCode() ?>

                <dt>
                <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="hidden" name="payment[method]" title="<?php echo $this->escapeHtml($_method->getTitle()) ?>" class="radio" <?php if ($this->getSelectedMethodCode() == $_code || $_code == 'free'): ?> checked="checked"<?php endif; ?> />
                <label for="p_method_<?php echo $_code ?>"><?php echo $_method->getTitle() ?></label></dt>
            <?php endforeach; ?>
        </dl>
    <?php else: ?>

        <dl class="sp-methods" id="checkout-payment-method-load">
            <?php foreach ($this->getMethods() as $_method): $_code = $_method->getCode() ?>
                <?php
                if ($_code == 'zipmoneypayment') {
                    $zip_title = Mage::getStoreConfig('payment/zipmoney_checkout/title');
                    ?>
                    <dt>
                    <?php if (sizeof($this->getMethods()) > 1): ?>
                        <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->escapeHtml($zip_title) ?>" class="radio validate-one-required-by-name" <?php if ($this->getSelectedMethodCode() == $_code || ($hide_nonfree_methods && $_code == 'free')): ?> checked="checked"<?php endif; ?> />
                    <?php else: ?>
                        <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" /></span>
                    <?php endif; ?>


                    <?php if (Mage::getStoreConfig('payment/zipmoney_checkout/displaylogo')): ?>
                        <label for="p_method_zipmoneypayment"><img width="40px" src="<?php echo $this->getSkinUrl('zipmoney/images/zipmoney-logo.png'); ?>" alt="zipMoney - Buy now Pay later!" class="v-middle" /> <?php echo $this->escapeHtml($zip_title) ?></label>&nbsp;<br />
                    <?php else: ?>
                        <label for="p_method_zipmoneypayment"><?php echo $this->escapeHtml($zip_title) ?></label>&nbsp;<br />
                    <?php endif; ?>


                    </dt>
                    <?php if ($html = $this->getChildHtml('payment.method.' . $_code)): ?>
                        <dd id="container_payment_method_<?php echo $_code; ?>" class="payment-method">
                            <?php echo $html; ?>
                        </dd>
                        <?php
                    endif;
                    continue;
                }
                ?>

                <?php if ($hide_nonfree_methods && $_code != 'free') continue; ?>
                <dt>
                <?php if (sizeof($this->getMethods()) > 1): ?>
                    <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->escapeHtml($_method->getTitle()) ?>" class="radio validate-one-required-by-name" <?php if ($this->getSelectedMethodCode() == $_code || ($hide_nonfree_methods && $_code == 'free')): ?> checked="checked"<?php endif; ?> />
                <?php else: ?>
                    <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" /></span>
                <?php endif; ?>
                <label for="p_method_<?php echo $_code ?>"><?php echo $_method->getTitle() ?></label>
                </dt>
                <?php if ($html = $this->getChildHtml('payment.method.' . $_code)): ?>
                    <dd id="container_payment_method_<?php echo $_code; ?>" class="payment-method">
                        <?php echo $html; ?>
                    </dd>
                <?php endif; ?>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>
</div>
<script type="text/javascript">
//<![CDATA[
$$('#checkout-payment-method-load dt input').invoke('observe', 'click', function(e) {
    var element = e.element();
    var name = 'payment_form_' + element.value;
    
    /* Hide all other forms */
    $$('dd.payment-method').invoke('hide');
    
    if(element.checked) {
        var form = $(name);
        var container = $('container_payment_method_' + element.value);

        if(element !== null && container !== null)    {
            container.show();
            $(name).show();
        }
    }    
});
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
    function toggleToolTip(event){
        if($('payment-tool-tip')){
            $('payment-tool-tip').setStyle({
                top: (Event.pointerY(event)-560)+'px'//,
                //left: (Event.pointerX(event)+100)+'px'
            })
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }
    if($('payment-tool-tip-close')){
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }
    
    initWhatIsCvvListeners();   
//]]>
</script>


<script type="text/javascript">
    if (window.ZipMoneyCheckoutWidgetModal == undefined) {
        var vInstanceName = 'window.ZipMoneyCheckoutWidgetModal';
        var vElementId = 'zipmoney-learn-more';
        var vDefaultContent = '<?php echo Mage::helper("zipmoneypayment/widget")->getDefaultContent(); ?>';
        var aPageContents = <?php echo json_encode(Mage::helper("zipmoneypayment/widget")->getCheckoutDialogPages()); ?>;
        try {
            window.ZipMoneyCheckoutWidgetModal = new WidgetModal(vInstanceName, vElementId, aPageContents, vDefaultContent);
        } catch (e) {
            if (typeof(window.ZipMoneyCheckoutWidgetModal) == 'undefined') {
                window.ZipMoneyCheckoutWidgetModal = {};
            }
            window.ZipMoneyCheckoutWidgetModal.showPopup = function() {alert('Sorry, can not load the content.')};
        }
    }
</script>

<?php if (Mage::helper('zipmoneypayment')->isIframeCheckoutEnabled()): ?>
    <script type="text/javascript">
        Event.observe(window, 'load', function() {
            if (<?php echo ((Mage::app()->getRequest()->getParam('zip') == 'iframe') ? 1 : 0); ?>) {
                var vUrl = '<?php echo Mage::getUrl('zipmoneypayment/Quote/getRedirectUrl', array('_secure' => true)); ?>';
                var iframe = new iframeCheckout(vUrl, 'onestepcheckout', '<?php echo $this->__('Can not redirect to zipMoney.') ?>');
                iframe.redirectToCheckout();
            }
        });
    </script>
<?php endif; ?>