<?php
/**
 * EaDesgin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@eadesign.ro so we can send you a copy immediately.
 *
 * @category    Eadesigndev_Shipestimation
 * @copyright   Copyright (c) 2008-2015 EaDesign by Eco Active S.R.L.
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
$ifTrue=Mage::Helper('shipestimation')->ifItApplies();
?>
<?php if ($ifTrue): ?>
    <div class="shipping-estimate">
        <a href="#calctransport" name="modal" onclick="openwindow()"><?php echo Mage::helper('checkout')->__('Estimate Shipping for This Item') ?></a>
    </div>
<?php endif ?>