<div id="menu-group-1"><ul class='level0 menu-creator-pro menu-creator-pro-fade menu-creator-pro-rp-switcher menu-creator-pro-cyan'><li class="switcher"><a href="#"><i class="mcp-icon fa-bars"></i>Menu</a>
</li><li class="  level0 col_0"><a title="<?php echo $this->__("Home") ?>" href="<?php echo $this->getMCPUrl() ?>" target="_self"><span><?php echo $this->__("Home") ?></span></a>
</li><li class="  mcpdropdown parent  level0 col_1"><a title="<?php echo $this->__("Apparel's Men") ?>" href="<?php echo $this->getMCPBaseUrl() ?>apparel.html" target="_self"data-hover='mcpdropdown'><span><?php echo $this->__("Apparel's Men") ?></span></a><span class="mcp-icon fa-angle-down"></span><div class='grid-container3'><ul><li class='autosub-item '><a title="<?php echo $this->__("Shirts 6&quot;") ?>" href="<?php echo $this->getMCPUrl()?>apparel/shirts.html"><?php echo $this->__("Shirts 6&quot;") ?></a>
</li><li class='autosub-item parent mcpdropdown has-submenu'><a title="<?php echo $this->__("Shoes") ?>" href="<?php echo $this->getMCPUrl()?>apparel/shoes.html"><?php echo $this->__("Shoes") ?></a><span class="mcp-icon fa-angle-down"></span><div class='grid-container3'><ul class='mcpdropdown-menu'><li class='level3 autosub-item '><a title="<?php echo $this->__("Mens 10&quot; vs 10'") ?>" href="<?php echo $this->getMCPUrl()?>apparel/shoes/mens.html"><?php echo $this->__("Mens 10&quot; vs 10'") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Womens") ?>" href="<?php echo $this->getMCPUrl()?>apparel/shoes/womens.html"><?php echo $this->__("Womens") ?></a>
</li></ul>

</div>

</li><li class='autosub-item parent mcpdropdown has-submenu'><a title="<?php echo $this->__("Hoodies") ?>" href="<?php echo $this->getMCPUrl()?>apparel/hoodies.html"><?php echo $this->__("Hoodies") ?></a><span class="mcp-icon fa-angle-down"></span><div class='grid-container3'><ul class='mcpdropdown-menu'><li class='level3 autosub-item '><a title="<?php echo $this->__("NAVIGATION") ?>" href="<?php echo $this->getMCPUrl()?>apparel/hoodies/navigation.html"><?php echo $this->__("NAVIGATION") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Menu Creator Pro") ?>" href="<?php echo $this->getMCPUrl()?>apparel/hoodies/menu-creator-pro.html"><?php echo $this->__("Menu Creator Pro") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Shop By Brands") ?>" href="<?php echo $this->getMCPUrl()?>apparel/hoodies/shop-by-brands.html"><?php echo $this->__("Shop By Brands") ?></a>
</li></ul>

</div>

</li></ul>

</div>

</li><li class="  mcpdropdown parent  level0 col_1"><a title="<?php echo $this->__("Menu 1") ?>" href=" #" target="_self"> <span class="title"><?php echo $this->__("Menu 1") ?></span></a><span class="mcp-icon fa-angle-down"></span><div class='grid-container3'><div class='grid-column grid-column3  '><a title="<?php echo $this->__("About") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>about-magento-demo-store" target="_self"><span><?php echo $this->__("About") ?></span></a><ul class='level1'><li class=' '><a title="<?php echo $this->__("HTC") ?>" href="<?php echo $this->getMCPUrl() ?>htc-touch-diamond.html" target="_self"><span><?php echo $this->__("HTC") ?></span></a>
</li><li class=' '><a title="<?php echo $this->__("Nokia") ?>" href="<?php echo $this->getMCPUrl() ?>nokia-2610-phone.html" target="_self"><span><?php echo $this->__("Nokia") ?></span></a>
</li></ul>

</div>

</div>

</li><li class="  mcpdropdown parent  level0 col_1"><a title="<?php echo $this->__("Electronics") ?>" href="<?php echo $this->getMCPBaseUrl() ?>electronics.html" target="_self"data-hover='mcpdropdown'><span><?php echo $this->__("Electronics") ?></span></a><span class="mcp-icon fa-angle-down"></span><div class='grid-container3'><ul><li class='autosub-item '><a title="<?php echo $this->__("Cell Phones") ?>" href="<?php echo $this->getMCPUrl()?>electronics/cell-phones.html"><?php echo $this->__("Cell Phones") ?></a>
</li><li class='autosub-item parent mcpdropdown has-submenu'><a title="<?php echo $this->__("Cameras") ?>" href="<?php echo $this->getMCPUrl()?>electronics/cameras.html"><?php echo $this->__("Cameras") ?></a><span class="mcp-icon fa-angle-down"></span><div class='grid-container3'><ul class='mcpdropdown-menu'><li class='level3 autosub-item '><a title="<?php echo $this->__("Accessories") ?>" href="<?php echo $this->getMCPUrl()?>electronics/cameras/accessories.html"><?php echo $this->__("Accessories") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Digital Cameras") ?>" href="<?php echo $this->getMCPUrl()?>electronics/cameras/digital-cameras.html"><?php echo $this->__("Digital Cameras") ?></a>
</li></ul>

</div>

</li><li class='autosub-item parent mcpdropdown has-submenu'><a title="<?php echo $this->__("Computers") ?>" href="<?php echo $this->getMCPUrl()?>electronics/computers.html"><?php echo $this->__("Computers") ?></a><span class="mcp-icon fa-angle-down"></span><div class='grid-container3'><ul class='mcpdropdown-menu'><li class='level3 autosub-item '><a title="<?php echo $this->__("Build Your Own") ?>" href="<?php echo $this->getMCPUrl()?>electronics/computers/build-your-own.html"><?php echo $this->__("Build Your Own") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Laptops") ?>" href="<?php echo $this->getMCPUrl()?>electronics/computers/laptops.html"><?php echo $this->__("Laptops") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Hard Drives") ?>" href="<?php echo $this->getMCPUrl()?>electronics/computers/hard-drives.html"><?php echo $this->__("Hard Drives") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Monitors") ?>" href="<?php echo $this->getMCPUrl()?>electronics/computers/monitors.html"><?php echo $this->__("Monitors") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("RAM / Memory") ?>" href="<?php echo $this->getMCPUrl()?>electronics/computers/ram-memory.html"><?php echo $this->__("RAM / Memory") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Cases") ?>" href="<?php echo $this->getMCPUrl()?>electronics/computers/cases.html"><?php echo $this->__("Cases") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Processors") ?>" href="<?php echo $this->getMCPUrl()?>electronics/computers/processors.html"><?php echo $this->__("Processors") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Peripherals") ?>" href="<?php echo $this->getMCPUrl()?>electronics/computers/peripherals.html"><?php echo $this->__("Peripherals") ?></a>
</li></ul>

</div>

</li><li class='autosub-item '><a title="<?php echo $this->__("Genarator") ?>" href="<?php echo $this->getMCPUrl()?>electronics/genarator.html"><?php echo $this->__("Genarator") ?></a>
</li></ul>

</div>

</li><li class="  mcpdropdown parent  level0 col_0"><a title="<?php echo $this->__("English's Menu") ?>" href=" <?php echo $this->getMCPUrl() ?>english" target="_self"> <span><?php echo $this->__("English's Menu") ?></span></a><span class="mcp-icon fa-angle-down"></span><div class='grid-container0'><div class='grid-column grid-column3  '><a title="<?php echo $this->__("US&quot; English") ?>" class="nav-header" href="#" target="_self"><span class="title"><?php echo $this->__("US&quot; English") ?></span></a><ul class='level1'><li class=' '><a title="<?php echo $this->__("North English &quot;") ?>" href="#" target="_self"><span class="title"><?php echo $this->__("North English &quot;") ?></span></a>
</li><li class='  mcpdropdown parent has-submenu'><a title="<?php echo $this->__("South&quot; English") ?>" href="#" target="_self"><span class="title"><?php echo $this->__("South&quot; English") ?></span></a><span class="mcp-icon fa-angle-down"></span><div class='grid-container3'><ul class='level2'><li class=' '><a title="<?php echo $this->__("Special ' vs &quot;") ?>" href="#" target="_self"><span class="title"><?php echo $this->__("Special ' vs &quot;") ?></span></a>
</li></ul>

</div>

</li></ul>

</div>

</div>

</li></ul>

</div>
