<ul class='dl-menu'><li/><a class="icon icon-home" title="<?php echo $this->__("Home") ?>" target="_self" href="<?php echo $this->getMCPUrl() ?>"><span><?php echo $this->__("Home") ?></span></a>
</li><li class=""><a class="icon icon-shop" title="<?php echo $this->__("Apparel's Men") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>apparel.html"><span><?php echo $this->__("Apparel's Men") ?></span></a><ul class='dl-submenu'><li class='autosub-item '><a title="<?php echo $this->__("Shirts 6&quot;") ?>" href="<?php echo $this->getMCPUrl()?>apparel/shirts.html"><?php echo $this->__("Shirts 6&quot;") ?></a>
</li><li class='autosub-item '><a title="<?php echo $this->__("Shoes") ?>" href="<?php echo $this->getMCPUrl()?>apparel/shoes.html"><?php echo $this->__("Shoes") ?></a><ul class='dl-submenu'><li class='level3 autosub-item '><a title="<?php echo $this->__("Mens 10&quot; vs 10'") ?>" href="<?php echo $this->getMCPUrl()?>apparel/shoes/mens.html"><?php echo $this->__("Mens 10&quot; vs 10'") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Womens") ?>" href="<?php echo $this->getMCPUrl()?>apparel/shoes/womens.html"><?php echo $this->__("Womens") ?></a>
</li></ul>

</li><li class='autosub-item '><a title="<?php echo $this->__("Hoodies") ?>" href="<?php echo $this->getMCPUrl()?>apparel/hoodies.html"><?php echo $this->__("Hoodies") ?></a><ul class='dl-submenu'><li class='level3 autosub-item '><a title="<?php echo $this->__("NAVIGATION") ?>" href="<?php echo $this->getMCPUrl()?>apparel/hoodies/navigation.html"><?php echo $this->__("NAVIGATION") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Menu Creator Pro") ?>" href="<?php echo $this->getMCPUrl()?>apparel/hoodies/menu-creator-pro.html"><?php echo $this->__("Menu Creator Pro") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Shop By Brands") ?>" href="<?php echo $this->getMCPUrl()?>apparel/hoodies/shop-by-brands.html"><?php echo $this->__("Shop By Brands") ?></a>
</li></ul>

</li></ul>

</li><li class=""><a class="" title="<?php echo $this->__("Menu 1") ?>" target="_self" href="#"><span class="title"><?php echo $this->__("Menu 1") ?></span></a><ul class="dl-submenu"><li class=""><a class="" title="<?php echo $this->__("About") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>about-magento-demo-store"><span><?php echo $this->__("About") ?></span></a><ul class="dl-submenu"><li/><a class="" title="<?php echo $this->__("HTC") ?>" target="_self" href="<?php echo $this->getMCPUrl() ?>htc-touch-diamond.html"><span><?php echo $this->__("HTC") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Nokia") ?>" target="_self" href="<?php echo $this->getMCPUrl() ?>nokia-2610-phone.html"><span><?php echo $this->__("Nokia") ?></span></a>
</li></ul>

</li></ul>

</li><li class=""><a class="icon icon-display" title="<?php echo $this->__("Electronics") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>electronics.html"><span><?php echo $this->__("Electronics") ?></span></a><ul class='dl-submenu'><li class='autosub-item '><a title="<?php echo $this->__("Cell Phones") ?>" href="<?php echo $this->getMCPUrl()?>electronics/cell-phones.html"><?php echo $this->__("Cell Phones") ?></a>
</li><li class='autosub-item '><a title="<?php echo $this->__("Cameras") ?>" href="<?php echo $this->getMCPUrl()?>electronics/cameras.html"><?php echo $this->__("Cameras") ?></a><ul class='dl-submenu'><li class='level3 autosub-item '><a title="<?php echo $this->__("Accessories") ?>" href="<?php echo $this->getMCPUrl()?>electronics/cameras/accessories.html"><?php echo $this->__("Accessories") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Digital Cameras") ?>" href="<?php echo $this->getMCPUrl()?>electronics/cameras/digital-cameras.html"><?php echo $this->__("Digital Cameras") ?></a>
</li></ul>

</li><li class='autosub-item '><a title="<?php echo $this->__("Computers") ?>" href="<?php echo $this->getMCPUrl()?>electronics/computers.html"><?php echo $this->__("Computers") ?></a><ul class='dl-submenu'><li class='level3 autosub-item '><a title="<?php echo $this->__("Build Your Own") ?>" href="<?php echo $this->getMCPUrl()?>electronics/computers/build-your-own.html"><?php echo $this->__("Build Your Own") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Laptops") ?>" href="<?php echo $this->getMCPUrl()?>electronics/computers/laptops.html"><?php echo $this->__("Laptops") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Hard Drives") ?>" href="<?php echo $this->getMCPUrl()?>electronics/computers/hard-drives.html"><?php echo $this->__("Hard Drives") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Monitors") ?>" href="<?php echo $this->getMCPUrl()?>electronics/computers/monitors.html"><?php echo $this->__("Monitors") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("RAM / Memory") ?>" href="<?php echo $this->getMCPUrl()?>electronics/computers/ram-memory.html"><?php echo $this->__("RAM / Memory") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Cases") ?>" href="<?php echo $this->getMCPUrl()?>electronics/computers/cases.html"><?php echo $this->__("Cases") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Processors") ?>" href="<?php echo $this->getMCPUrl()?>electronics/computers/processors.html"><?php echo $this->__("Processors") ?></a>
</li><li class='level3 autosub-item '><a title="<?php echo $this->__("Peripherals") ?>" href="<?php echo $this->getMCPUrl()?>electronics/computers/peripherals.html"><?php echo $this->__("Peripherals") ?></a>
</li></ul>

</li><li class='autosub-item '><a title="<?php echo $this->__("Genarator") ?>" href="<?php echo $this->getMCPUrl()?>electronics/genarator.html"><?php echo $this->__("Genarator") ?></a>
</li></ul>

</li><li class=""><a class="" title="<?php echo $this->__("English's Menu") ?>" target="_self" href="<?php echo $this->getMCPUrl() ?>english"><span><?php echo $this->__("English's Menu") ?></span></a><ul class="dl-submenu"><li class=""><a class="" title="<?php echo $this->__("US&quot; English") ?>" target="_self" href="#"><span class="title"><?php echo $this->__("US&quot; English") ?></span></a><ul class="dl-submenu"><li/><a class="" title="<?php echo $this->__("North English &quot;") ?>" target="_self" href="#"><span class="title"><?php echo $this->__("North English &quot;") ?></span></a>
</li><li class=""><a class="" title="<?php echo $this->__("South&quot; English") ?>" target="_self" href="#"><span class="title"><?php echo $this->__("South&quot; English") ?></span></a><ul class="dl-submenu"><li/><a class="" title="<?php echo $this->__("Special ' vs &quot;") ?>" target="_self" href="#"><span class="title"><?php echo $this->__("Special ' vs &quot;") ?></span></a>
</li></ul>

</li></ul>

</li></ul>

</li></ul>
