<?php 
$title = Mage::getStoreConfig('cattabs/general/title');
$identify = $this->generateRandomString();
$tabs = $this->getTabs(); 
if (Mage::app()->getStore()->isCurrentlySecure()) {
	$url = $this->getUrl('cattabs/index/ajax', array('_secure'=>true));
}else{
	$url = $this->getUrl('cattabs/index/ajax');
}
?>
<div class="cattabproducts">
	<div id="<?php echo $identify ?>" class="categories-tabs">
		<?php echo $title ? '<div class="bx-title"><h2>'.$this->__($title).'</h2></div>' : ''; ?>
		<ul class="cattabs" data-options=<?php echo $this->getOptions() ?>>
			<?php
				$active = ' active';
				foreach ($tabs as $id => $name) {
					echo '<li data-catid ="'.$id.'" class="item'.$active.'">'.$name.'</li>';
					$active = '';
				}
			?>
		</ul>	
		<div class="ajax_loading" style="display:none">
			<i class="fa fa-spinner fa-spin"></i>
		</div>
		<div class="cattabs-products"></div>
	</div>
<script type="text/javascript">
	jQuery( document ).ready(function($) {
		(function(selector){
			var $content = $(selector);
			var cattabs  = $('.cattabs', $content);
			var options  = cattabs.data('options');
			var $items 	 = $('.item', cattabs);
			var $loading = $(".ajax_loading", $content);
			var $products= $('.cattabs-products', $content);
			var info 	 = {catId:$items.first().data('catid')};
			$.extend(info, options);
			$items.click(function() {
				info = {catId:$(this).data('catid')};
				$.extend(info, options);
				if($(this).hasClass('active')) return;
				$items.removeClass('active');
				$(this).addClass('active');
				getProduct(info);
			});
			getProduct(info);
			function getProduct(data) {
				$loading.show();
				$.ajax({
					type:'post',
					data: data,
					url:'<?php echo $url ?>',
					success: function(data){
						$loading.hide();
						$products.html(data);		
						$data = data;
						$('.products-grid', $products).owlCarousel({
								autoplay: false, 
								nav: true, 
								dots: false, 
								loop: <?php echo ($this->getConfig('loop') == 1? "true": "false") ?>,
								responsive: {<?php echo ($this->getResponsive()?$this->getResponsive():$this->getConfig('responsive')) ?>},
								margin: <?php echo $this->getConfig('margin') ?>
								//padding: 10
							})
					},
				});		 
			}
		})("#<?php echo $identify ?>");
	});
</script>
</div>

