                <div style="clear:both;"></div>
        <div style="padding:20px 0;">
<?php /*
    <div class="col-sm-4 "><a href="commuter/"> <img alt="" src="<?php echo $this->getUrl(); ?>media/wysiwyg/SLIDERB-COMMUTER.jpg" style="width:100%;"/></a></div>
    <div class="col-sm-4 "><a href="commuter/"> <img alt="" src="<?php echo $this->getUrl(); ?>media/wysiwyg/SLIDERB-COMMUTER.jpg" style="width:100%;"/></a></div>
    <div class="col-sm-4 "><a href="commuter/"> <img alt="" src="<?php echo $this->getUrl(); ?>media/wysiwyg/SLIDERB-COMMUTER.jpg" style="width:100%;"/></a></div>
    --> */ ?>
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('banner_partners')->toHtml(); ?>
</div>
     <div style="clear:both;"></div>
        <div style="padding:20px 0;">
        	<div class="container">
                         <h3 class="heading-title" style="text-transform:uppercase;">Bikes - Hot Specials!</h3>
<?php echo $this->getLayout()->createBlock('featuredproduct/list')->setCategoryId(9)->setTemplate('themevast/featuredproduct/featuredproduct-new.phtml')->tohtml(); ?>
        	</div>
        </div>
     <?php /*
     <div style="clear:both;"></div>
        <div style="padding:20px 0;">
        	<div class="container">
                         <h3 class="heading-title" style="text-transform:uppercase;">Clearance Specials!</h3>
<?php echo $this->getLayout()->createBlock('featuredproduct/all')->setCategoryId(356)->setTemplate('themevast/featuredproduct/featuredproduct-new.phtml')->tohtml(); ?>
        	</div>
        </div> */ ?>
        <div style="clear:both;"></div>
        <div class="awesome-accesories" style="padding:20px 15px 20px 0; background:#fff;">
        <h3 class="heading-title">We Also Have a Full Range of Accessories</h3>
    <div class="col-xs-6 col-sm-2"><a href="<?php echo $this->getUrl(); ?>bike-accessories/"> <img alt="" src="<?php echo $this->getUrl(); ?>media/wysiwyg/catcol-view-all-acc.jpg" style="width:100%;"/> </a> </div>
    <div class="col-xs-6 col-sm-2"><a href="<?php echo $this->getUrl(); ?>bike-accessories/pumps/"><img alt="" src="<?php echo $this->getUrl(); ?>media/wysiwyg/Pumps.jpg" style="width:100%;"/></a></div>
    <div class="col-xs-6 col-sm-2"><a href="<?php echo $this->getUrl(); ?>bike-accessories/locks/"><img alt="" src="<?php echo $this->getUrl(); ?>media/wysiwyg/Locks.jpg" style="width:100%;"/></a></div>
    <div class="col-xs-6 col-sm-2"><a href="<?php echo $this->getUrl(); ?>bike-accessories/lights/"><img alt="" src="<?php echo $this->getUrl(); ?>media/wysiwyg/Lights.jpg" style="width:100%;"/></a></div>
    <div class="col-xs-6 col-sm-2"><a href="<?php echo $this->getUrl(); ?>bike-accessories/helmets/"> <img alt="" src="<?php echo $this->getUrl(); ?>media/wysiwyg/Helmets.jpg" style="width:100%;"/></a></div>
    <div class="col-xs-6 col-sm-2"> <a href="<?php echo $this->getUrl(); ?>parts/"><img alt="" src="<?php echo $this->getUrl(); ?>media/wysiwyg/SLIDERB-PARTS.jpg" style="width:100%;"/></a></div>
<div style="clear:both;"></div>
</div>
     <div style="clear:both;"></div>
        <div style="padding:20px 0; background:#fff;">
        	<div class="container">
             <h3 class="heading-title">Accessories - Hot Specials!</h3>
<?php echo $this->getLayout()->createBlock('featuredproduct/list')->setCategoryId(17)->setTemplate('themevast/featuredproduct/featuredproduct-new.phtml')->tohtml(); ?>
        	</div>
        </div>
        <div style="clear:both;"></div>
<div class="banner-content" style="margin:20px 0;">
<div class="banner-box col-sm-6"><a title="Buzz Rack Bike Carriers" href="/brands/buzz-rack/"><img title="Buzz Rack Most Popular Bike Carriers - View All Models" alt="Buzz Rack Most Popular Bike Carriers Banner" src="<?php echo $this->getUrl(); ?>media/wysiwyg/DOUBLE-BANNER-BUZZ.jpg" style="width:100%"></a></div>
<div class="banner-box col-sm-6"><a href="https://www.bikes.com.au/electric/"><img title="Electric Bikes Available" alt="Electric Bikes" src="<?php echo $this->getUrl(); ?>media/wysiwyg/DOUBLE-BANNER-EBIKE.jpg" style="width:100%"></a></div>
</div>
        <div style="clear:both;"></div>        