<?php $buttonTitle = $this->__('zipMoney Express'); ?>
<div class="zipmoney-express-button-cart-wrapper">
    <div id="zipmoney-express-cart" style="text-align:center">           
        <a id="zipmoney-express-button" zm-asset="cartbutton" zm-widget="inline" style="cursor: pointer;" title="<?php echo $buttonTitle; ?>" style="cursor: pointer;" 
        <?php if(!$this->_isIframeFlowEnabled()) echo "href='".htmlentities($this->getExpressPaymentUrl())."'" ?> > </a>
        <a id="zipmoney-express-learn-more" zm-asset="cartbuttonlink" zm-widget="popup"  zm-popup-asset="termsdialog"  class="zip-hover zip-express-widget-link" style="font-family: Noto Sans; color: #808080; font-size: 9px;" ></a>
    </div>
    <span class="zip-cart-please-wait" id="redirecting-to-zipmoney" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Redirecting to zipMoney...') ?>" title="<?php echo $this->__('Redirecting to zipMoney...') ?>" class="v-middle" /> 
        <?php echo $this->__('Redirecting to zipMoney...') ?>
    </span>
</div>
<?php if($this->_isIframeFlowEnabled()): ?>
<script type="text/javascript">
    document.observe("dom:loaded", function () {
        var parentElement = this;
        $$('#zipmoney-express-button').each(function (oEle) {
            if (oEle == undefined) {
                return;
            }
            oEle.observe('click', function (oEvent) {
                oEvent.preventDefault();
                showRedirectingText();
                var vUrl = '<?php echo $this->getIframeRedirectUrl(); ?>';
                var iframe = new iframeCheckout(vUrl, 'cart', '<?php echo $this->__('Can not redirect to zipMoney.') ?>');
                iframe.redirectToCheckout();
                Event.stop(oEvent);
            });
        });
    });
</script>
<?php endif; ?>