<table class="form-list">
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getUrl('*/magicscroll_cache/clean/'); ?>')" type="button" class="scalable"><span><span><span><?php echo Mage::helper('adminhtml')->__('Flush Magic Scroll&#8482; Images Cache'); ?></span></span></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('adminhtml')->__('Pregenerated Magic Scroll&#8482; images files.'); ?>
        </td>
    </tr>
</table>
