<div class="nav-vcontainer hidden-xs hidden-sm">
    <div class="nav-inner">
         <div class="block"><div class="block-title"><strong><?php echo $this->__('Categories') ?></strong></div></div>
        <div class="vmegamenu-contain">
            <ul id="accordion" class="nav_vmegamenu">
                <?php $megamenu =  $this->getLayout()->createBlock('megamenu/megamenu'); ?>       
                <?php echo $megamenu->drawMegamenuMain(); ?>        
            </ul>
        </div>
    </div>
    <script type="text/javascript">
        //<![CDATA[
        var MEGAMENU_EFFECT = <?php echo (int)Mage::getStoreConfig('megamenu/general/effect')?>;
        
        //]]>
    </script>

</div>
