<a class="menu-opener" href="#"><?php echo $this->__("open") ?></a>
<div id="menu-group-1">
	<a class="btn-close" href="#"><?php echo $this->__("close") ?></a>
	<div class="menu-holder">
		<ul class='active level0 menu-creator-pro menu-creator-pro-fade mcp-multilevel-style-5 menu-creator-pro-purple'>
			</li><li class="  level0 col_1">
				<a style="color:#f9f609;" title="<?php echo $this->__("Clearance Sale") ?>" href="<?php echo $this->getMCPBaseUrl() ?>clearance-sale/" target="_self"><span><?php echo $this->__("Clearance Sale") ?></span></a>
			</li>
			<li class="  mcpdropdown parent  level0 col_3">
				<a title="<?php echo $this->__("Bikes") ?>" href=" #" target="_self">
					<span class="title"><?php echo $this->__("Bikes") ?></span>
				</a>
				<span class="mcp-icon fa-angle-down"></span>
				<div class='grid-container3'>
					<div class='grid-column grid-column3 custom-dropdown mobile'>
						<a title="back" class="nav-header btn-back" href="#"><span>&lt; <?php echo $this->__("Back") ?></span></a>
					</div>
					<div class='grid-column grid-column3 custom-dropdown '>
						<a title="<?php echo $this->__("Retro / Vintage") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>vintage-retro-bikes/" target="_self">
							<img class="lazy" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/tv_bikeworld_package/tv_bikeworld2/images/retro vintage.png'; ?>" alt="<?php echo $this->__("Retro / Vintage")  ?>" width="154" height="107"/>
							<span><?php echo $this->__("Retro / Vintage") ?></span>
						</a>
					</div>
					<div class='grid-column grid-column3 custom-dropdown '>
						<a title="<?php echo $this->__("Road") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>buy-road-bikes/" target="_self">
							<img class="lazy" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/tv_bikeworld_package/tv_bikeworld2/images/road_example_v2_white.png'; ?>" alt="<?php echo $this->__("Lights") ?>" width="145" height="88"/>
							<span><?php echo $this->__("Road") ?></span>
						</a>
						<div class='grid-container3'>
							<ul>
								<li class='autosub-item mobile'>
									<a title="Back" class="btn-back" href="#">&lt; <?php echo $this->__("Back") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("Racing Bikes") ?>" href="<?php echo $this->getMCPUrl() ?>buy-road-bikes/racing/"><?php echo $this->__("Racing Bikes") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("Cyclocross Bikes") ?>" href="<?php echo $this->getMCPUrl() ?>buy-road-bikes/cyclocross/"><?php echo $this->__("Cyclocross Bikes") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("Endurance Bikes") ?>" href="<?php echo $this->getMCPUrl() ?>buy-road-bikes/endurance/"><?php echo $this->__("Endurance Bikes") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("Sport Bikes") ?>" href="<?php echo $this->getMCPUrl() ?>buy-road-bikes/sport/"><?php echo $this->__("Sport Bikes") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("Triathlon Bikes") ?>" href="<?php echo $this->getMCPUrl() ?>buy-road-bikes/triathlon/"><?php echo $this->__("Triathlon Bikes") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("Touring Bikes") ?>" href="<?php echo $this->getMCPUrl() ?>buy-road-bikes/touring/"><?php echo $this->__("Touring Bikes") ?></a>
								</li>
							</ul>
						</div>
					</div>
					<div class='grid-column grid-column3 custom-dropdown '>
						<a title="<?php echo $this->__("Electric") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>electric-bike/" target="_self">
							<img class="lazy" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"  data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/tv_bikeworld_package/tv_bikeworld2/images/electric.png'; ?>" alt="<?php echo $this->__("Electric") ?>" width="200" height="112"/>
							<span><?php echo $this->__("Electric") ?></span>
						</a>
					</div>
					<div class='grid-column grid-column3 custom-dropdown '>
						<a title="<?php echo $this->__("Mountain") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>buy-cheap-mountain-bikes/" target="_self">
							<img class="lazy" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/tv_bikeworld_package/tv_bikeworld2/images/mountain.png'; ?>" alt="<?php echo $this->__("Mountain") ?>" width="157" height="100"/>
							<span><?php echo $this->__("Mountain") ?></span>
						</a>
						<div class='grid-container3'>
							<ul>
								<li class='autosub-item mobile'>
									<a title="Back" class="btn-back" href="#">&lt; <?php echo $this->__("Back") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("Dirt Jump Bikes") ?>" href="<?php echo $this->getMCPUrl() ?>buy-cheap-mountain-bikes/dirt-jump/"><?php echo $this->__("Dirt Jump Bikes") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("Downhill Bikes") ?>" href="<?php echo $this->getMCPUrl() ?>buy-cheap-mountain-bikes/downhill/"><?php echo $this->__("Downhill Bikes") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("Dual Suspension Bikes") ?>" href="<?php echo $this->getMCPUrl() ?>buy-cheap-mountain-bikes/dual-suspension/"><?php echo $this->__("Dual Suspension Bikes") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("Recreational Bikes") ?>" href="<?php echo $this->getMCPUrl() ?>buy-cheap-mountain-bikes/recreational/"><?php echo $this->__("Recreational Bikes") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("Trail Hardtail Bikes") ?>" href="<?php echo $this->getMCPUrl() ?>buy-cheap-mountain-bikes/trail-hardtail/"><?php echo $this->__("Trail Hardtail Bikes") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("XC Hardtail Bikes") ?>" href="<?php echo $this->getMCPUrl() ?>buy-cheap-mountain-bikes/xc-hardtail/"><?php echo $this->__("XC Hardtail Bikes") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("Fat Bikes") ?>" href="<?php echo $this->getMCPUrl() ?>buy-cheap-mountain-bikes/fat/"><?php echo $this->__("Fat Bikes") ?></a>
								</li>
							</ul>
						</div>
					</div>
					<div class='grid-column grid-column3 custom-dropdown '>
						<a title="<?php echo $this->__("Commuter") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>commuter/" target="_self">
							<img class="lazy" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/tv_bikeworld_package/tv_bikeworld2/images/commuter.png'; ?>" alt="<?php echo $this->__("Commuter") ?>" width="268" height="169"/>
							<span><?php echo $this->__("Commuter") ?></span>
						</a>
						<div class='grid-container3'>
							<ul>
								<li class='autosub-item mobile'>
									<a title="Back" class="btn-back" href="#">&lt; <?php echo $this->__("Back") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("Fixie Bikes") ?>" href="<?php echo $this->getMCPUrl() ?>commuter/fixie-single-speed/"><?php echo $this->__("Fixie Bikes") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("Flat Bar Road Bikes") ?>" href="<?php echo $this->getMCPUrl() ?>commuter/flat-bar-road/"><?php echo $this->__("Flat Bar Road Bikes") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("Urban Bikes") ?>" href="<?php echo $this->getMCPUrl() ?>commuter/urban/"><?php echo $this->__("Urban Bikes") ?></a>
								</li>
							</ul>
						</div>
					</div>
					<div class='grid-column grid-column3 custom-dropdown '>
						<a title="<?php echo $this->__("Hybrid") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>hybrid/" target="_self">
							<img class="lazy" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/tv_bikeworld_package/tv_bikeworld2/images/hybrid.png'; ?>" alt="<?php echo $this->__("hybrid") ?>" width="272" height="172"/>
							<span><?php echo $this->__("Hybrid") ?></span>
						</a>
					</div>
					<?php /**<div class='grid-column grid-column3 custom-dropdown '><a title="<?php echo $this->__("Electric") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>electric-bike/" target="_self"><span><?php echo $this->__("Electric") ?></span></a>
					 * </div> */ ?>
					<div class='grid-column grid-column3 custom-dropdown '>
						<a title="<?php echo $this->__("Kids") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>kids/" target="_self">
							<img class="lazy" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/tv_bikeworld_package/tv_bikeworld2/images/kids.png'; ?>" alt="<?php echo $this->__("hybrid") ?>" width="207" height="150"/>
							<span><?php echo $this->__("Kids") ?></span>
						</a>
						<div class='grid-container3'>
							<ul>
								<li class='autosub-item mobile'>
									<a title="Back" class="btn-back" href="#">&lt; <?php echo $this->__("Back") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("Single Speed Bikes") ?>" href="<?php echo $this->getMCPUrl() ?>kids/single-speed/"><?php echo $this->__("Single Speed Bikes") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("Geared Bikes") ?>" href="<?php echo $this->getMCPUrl() ?>kids/geared/"><?php echo $this->__("Geared Bikes") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("Balance Bikes") ?>" href="<?php echo $this->getMCPUrl() ?>kids/balance/"><?php echo $this->__("Balance Bikes") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("Tricycles") ?>" href="<?php echo $this->getMCPUrl() ?>kids/tricycles/"><?php echo $this->__("Tricycles") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("Scooters") ?>" href="<?php echo $this->getMCPUrl() ?>kids/scooters/"><?php echo $this->__("Scooters") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("Tag Along Bikes") ?>" href="<?php echo $this->getMCPUrl() ?>kids/tag-along/"><?php echo $this->__("Tag Along Bikes") ?></a>
								</li>
							</ul>
						</div>
					</div>
					<?php /**<div class='grid-column grid-column3 custom-dropdown '><a title="<?php echo $this->__("Retro / Vintage") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>vintage-retro-bikes/" target="_self"><span><?php echo $this->__("Retro / Vintage") ?></span></a>
					 * </div> */ ?>
					<div class='grid-column grid-column3 custom-dropdown '>
						<a title="<?php echo $this->__("Cruiser") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>cruiser/" target="_self">
							<img class="lazy" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/tv_bikeworld_package/tv_bikeworld2/images/cruiser v1.png'; ?>" alt="<?php echo $this->__("Trikes") ?>" width="269" height="173"/>
							<span><?php echo $this->__("Cruiser") ?></span>
						</a>
					</div>
					<div class='grid-column grid-column3 custom-dropdown '>
						<a title="<?php echo $this->__("BMX") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bmx/" target="_self">
							<img class="lazy" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/tv_bikeworld_package/tv_bikeworld2/images/bmx.png'; ?>" alt="<?php echo $this->__("BMX") ?>" width="151" height="100"/>
							<span><?php echo $this->__("BMX") ?></span>
						</a>
						<div class='grid-container3'>
							<ul>
								<li class='autosub-item mobile'>
									<a title="Back" class="btn-back" href="#">&lt; <?php echo $this->__("Back") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("Street BMX Bikes") ?>" href="<?php echo $this->getMCPUrl() ?>bmx/street/"><?php echo $this->__("Street BMX Bikes") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("Cruiser BMX Bikes") ?>" href="<?php echo $this->getMCPUrl() ?>bmx/cruiser/"><?php echo $this->__("Cruiser BMX Bikes") ?></a>
								</li>
								<li class='autosub-item '>
									<a title="<?php echo $this->__("Retro BMX Bikes") ?>" href="<?php echo $this->getMCPUrl() ?>bmx/retro/"><?php echo $this->__("Retro BMX Bikes") ?></a>
								</li>
							</ul>
						</div>
					</div>
					<div class='grid-column grid-column3 custom-dropdown '>
						<a title="<?php echo $this->__("Folding") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>folding/" target="_self">
							<img class="lazy" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/tv_bikeworld_package/tv_bikeworld2/images/folding.png'; ?>" alt="<?php echo $this->__("Folding") ?>" width="157" height="112"/>
							<span><?php echo $this->__("Folding") ?></span>
						</a>
					</div>
					<div class='grid-column grid-column3 custom-dropdown '>
						<a title="<?php echo $this->__("Trikes") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>trikes/" target="_self">
							<img class="lazy" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/tv_bikeworld_package/tv_bikeworld2/images/trike v2.png'; ?>" alt="<?php echo $this->__("Trikes") ?>" width="398" height="326"/>
							<span><?php echo $this->__("Trikes") ?></span>
						</a>
					</div>
				</div>
			</li><li class="  mcpdropdown parent  level0 col_9">
				<a title="<?php echo $this->__("Accessories") ?>" href=" <?php echo $this->getMCPBaseUrl() ?>bike-accessories/" target="_self">
					<span><?php echo $this->__("Accessories") ?></span>
				</a>
				<span class="mcp-icon fa-angle-down"></span>
				<div class='grid-container9'>
					<div class='grid-column grid-column3 mobile'>
						<a title="back" class="nav-header btn-back" href="#"><span>&lt; <?php echo $this->__("Back") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Lights") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/lights/" target="_self">
							<?php /* <img class="lazy" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-src="/skin/frontend/tv_bikeworld_package/tv_bikeworld2/images/light.png" alt="<?php echo $this->__("Lights") ?>" width="888" height="740"/> */ ?>
							<span><?php echo $this->__("Lights") ?></span>
						</a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Helmets") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/helmets/" target="_self">
							<?php /* <img class="lazy" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-src="/skin/frontend/tv_bikeworld_package/tv_bikeworld2/images/helmet.png" alt="<?php echo $this->__("Helmets") ?>" width="512" height="512"/> */ ?>
							<span><?php echo $this->__("Helmets") ?></span>
						</a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Locks") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/locks/" target="_self">
							<?php /* <img class="lazy" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-src="/skin/frontend/tv_bikeworld_package/tv_bikeworld2/images/lock-v1.png" alt="<?php echo $this->__("Locks") ?>" width="872" height="740"/> */ ?>
							<span><?php echo $this->__("Locks") ?></span>
						</a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Baby Seats") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/child-seats/" target="_self"><span><?php echo $this->__("Baby Seats") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Grips") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/grips/" target="_self"><span><?php echo $this->__("Grips") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Mudguards") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/mudguards/" target="_self"><span><?php echo $this->__("Mudguards") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Backpacks") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/backpacks/" target="_self"><span><?php echo $this->__("Backpacks") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Handlebar Tape") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/handlebar-tape/" target="_self"><span><?php echo $this->__("Handlebar Tape") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Nutrition") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/nutrition/" target="_self"><span><?php echo $this->__("Nutrition") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Bags &amp; Panniers") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/bags/" target="_self"><span><?php echo $this->__("Bags &amp; Panniers") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Pegs") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/bmx-pegs/" target="_self"><span><?php echo $this->__("Pegs") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Bar Ends") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/bar-ends/" target="_self"><span><?php echo $this->__("Bar Ends") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Home Trainers") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/home-trainers/" target="_self"><span><?php echo $this->__("Home Trainers") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Pumps") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/pumps/" target="_self"><span><?php echo $this->__("Pumps") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Baskets") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/baskets/" target="_self"><span><?php echo $this->__("Baskets") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Kickstands") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/kickstands/" target="_self"><span><?php echo $this->__("Kickstands") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Racks") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/carry-racks/" target="_self"><span><?php echo $this->__("Racks") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Bells &amp; Horns") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/bells-horns/" target="_self"><span><?php echo $this->__("Bells &amp; Horns") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Kids Bike Accessories") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/kids-bike-accessories/" target="_self"><span><?php echo $this->__("Kids Bike Accessories") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Storage &amp; Stands") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/storage-and-stands/" target="_self"><span><?php echo $this->__("Storage &amp; Stands") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Bike Covers") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/covers/" target="_self"><span><?php echo $this->__("Bike Covers") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Sunscreen") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/sunscreen/" target="_self"><span><?php echo $this->__("Sunscreen") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Bottle Cages") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/bottle-cages/" target="_self"><span><?php echo $this->__("Bottle Cages") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Tools") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/tools/" target="_self"><span><?php echo $this->__("Tools") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Car Racks") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/carriers-racks/" target="_self"><span><?php echo $this->__("Car Racks") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Lubrication") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/lubrication-cleaning/" target="_self"><span><?php echo $this->__("Lubrication") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Trailers") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/trailers/" target="_self"><span><?php echo $this->__("Trailers") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Chamois Cream") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/chamois-cream/" target="_self"><span><?php echo $this->__("Chamois Cream") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Maps &amp; Books") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/books/" target="_self"><span><?php echo $this->__("Maps &amp; Books") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Tyre Sealant") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/tyre-sealant/" target="_self"><span><?php echo $this->__("Tyre Sealant") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Computers") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/computers/" target="_self"><span><?php echo $this->__("Computers") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Mirrors") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/mirrors/" target="_self"><span><?php echo $this->__("Mirrors") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Water Bottles") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/water-bottles/" target="_self"><span><?php echo $this->__("Water Bottles") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Gift Vouchers") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/gift-vouchers/" target="_self"><span><?php echo $this->__("Gift Vouchers") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Mobile Accessories") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/mobile-phone-accessories/" target="_self"><span><?php echo $this->__("Mobile Accessories") ?></span></a>
					</div>
				</div>
			</li><li class="  mcpdropdown parent  level0 col_9">
				<a title="<?php echo $this->__("Parts") ?>" href=" <?php echo $this->getMCPBaseUrl() ?>parts/" target="_self">
					<span><?php echo $this->__("Parts") ?></span>
				</a>
				<span class="mcp-icon fa-angle-down"></span>
				<div class='grid-container9'>
					<div class='grid-column grid-column3 mobile'>
						<a title="back" class="nav-header btn-back" href="#"><span>&lt; <?php echo $this->__("Back") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Axles &amp; Skewers") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>parts/axles-skewers/" target="_self"><span><?php echo $this->__("Axles &amp; Skewers") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Forks") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>parts/forks/" target="_self"><span><?php echo $this->__("Forks") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Seat Posts") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>parts/seat-posts/" target="_self"><span><?php echo $this->__("Seat Posts") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Batteries") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>parts/light-batteries/" target="_self"><span><?php echo $this->__("Batteries") ?></span></a>
					</div>
					<div class='grid-column grid-column3 custom-dropdown '>
						<a title="<?php echo $this->__("Freewheels") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>parts/freewheels-sprockets/" target="_self"><span><?php echo $this->__("Freewheels") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Shifters") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>parts/shifters/" target="_self"><span><?php echo $this->__("Shifters") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Bottom Brackets") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>parts/bottom-brackets/" target="_self"><span><?php echo $this->__("Bottom Brackets") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Handlebars") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>parts/handlebars/" target="_self"><span><?php echo $this->__("Handlebars") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Stems") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>parts/stems/" target="_self"><span><?php echo $this->__("Stems") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Brakes") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>parts/brakes/" target="_self"><span><?php echo $this->__("Brakes") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Headsets") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>parts/headsets/" target="_self"><span><?php echo $this->__("Headsets") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Tubes") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>parts/tubes/" target="_self"><span><?php echo $this->__("Tubes") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Chains") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>parts/chains/" target="_self"><span><?php echo $this->__("Chains") ?></span></a>
					</div>
					<div class='grid-column grid-column3 custom-dropdown '>
						<a title="<?php echo $this->__("Pedals &amp; Cleats") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>parts/pedals/" target="_self"><span><?php echo $this->__("Pedals &amp; Cleats") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Tyres") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>parts/tyres/" target="_self"><span><?php echo $this->__("Tyres") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Crank Sets") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>parts/crank-sets/" target="_self"><span><?php echo $this->__("Crank Sets") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Saddles") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>parts/seats/" target="_self"><span><?php echo $this->__("Saddles") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Wheels") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>parts/wheels/" target="_self"><span><?php echo $this->__("Wheels") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Derailleurs") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>parts/derailleurs/" target="_self"><span><?php echo $this->__("Derailleurs") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Derailleur Hangers") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-derailleur-hangers" target="_self"><span><?php echo $this->__("Derailleur Hangers") ?></span></a>
					</div>
				</div>
			</li><li class="  mcpdropdown parent  level0 col_9">
				<a title="<?php echo $this->__("Clothing") ?>" href=" <?php echo $this->getMCPBaseUrl() ?>clothing/" target="_self">
					<span><?php echo $this->__("Clothing") ?></span>
				</a>
				<span class="mcp-icon fa-angle-down"></span>
				<div class='grid-container9'>
					<div class='grid-column grid-column3 mobile'>
						<a title="back" class="nav-header btn-back" href="#"><span>&lt; <?php echo $this->__("Back") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Arm Warmers") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>clothing/arm-warmers/" target="_self"><span><?php echo $this->__("Arm Warmers") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Jerseys") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>clothing/jerseys/" target="_self"><span><?php echo $this->__("Jerseys") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Shoes") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>clothing/shoes/" target="_self"><span><?php echo $this->__("Shoes") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Bib Knicks") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>clothing/bib-shorts/" target="_self"><span><?php echo $this->__("Bib Knicks") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Knee Warmers") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>clothing/knee-warmers/" target="_self"><span><?php echo $this->__("Knee Warmers") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Shoe Covers") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>clothing/shoe-covers/" target="_self"><span><?php echo $this->__("Shoe Covers") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Body Armour") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>clothing/body-armour-crash-pads/" target="_self"><span><?php echo $this->__("Body Armour") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Knicks &amp; Shorts") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>clothing/shorts-knicks/" target="_self"><span><?php echo $this->__("Knicks &amp; Shorts") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Socks") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>clothing/socks/" target="_self"><span><?php echo $this->__("Socks") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Gloves") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>clothing/gloves/" target="_self"><span><?php echo $this->__("Gloves") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Leg Warmers") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>clothing/leg-warmers/" target="_self"><span><?php echo $this->__("Leg Warmers") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Sunglasses") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>clothing/sunglasses/" target="_self"><span><?php echo $this->__("Sunglasses") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Head &amp; Ear Warmers") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>clothing/head-ear-warmers/" target="_self"><span><?php echo $this->__("Head &amp; Ear Warmers") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Safety Gear") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>clothing/safety-gear/" target="_self"><span><?php echo $this->__("Safety Gear") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Tights") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>clothing/tights/" target="_self"><span><?php echo $this->__("Tights") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Jackets") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>clothing/jackets/" target="_self"><span><?php echo $this->__("Jackets") ?></span></a>
					</div>
				</div>
			</li><li class="  mcpdropdown parent  level0 col_2">
				<a title="<?php echo $this->__("Repairs") ?>" href=" #" target="_self">
					<span class="title"><?php echo $this->__("Repairs") ?></span>
				</a>
				<span class="mcp-icon fa-angle-down"></span>
				<div class='grid-container2'>
					<div class='grid-column grid-column3 mobile'>
						<a title="back" class="nav-header btn-back" href="#"><span>&lt; <?php echo $this->__("Back") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("In Store Repairs") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>bike-servicing/" target="_self"><span><?php echo $this->__("In Store Repairs") ?></span></a>
					</div>
					<div class='grid-column grid-column3  '>
						<a title="<?php echo $this->__("Mobile Mechanic Service") ?>" class="nav-header" href="<?php echo $this->getMCPBaseUrl() ?>mbc-mobile-mechanic-service/" target="_self"><span><?php echo $this->__("Mobile Mechanic Service") ?></span></a>
					</div>
				</div>
			</li><li class="  level0 col_1">
				<a title="<?php echo $this->__("Brands") ?>" href="<?php echo $this->getMCPBaseUrl() ?>brands/" target="_self"><span><?php echo $this->__("Brands") ?></span></a>
			</li><li class="  level0 col_2">
				<a title="<?php echo $this->__("Contact Us") ?>" href="<?php echo $this->getMCPBaseUrl() ?>contacts/" target="_self"><span><?php echo $this->__("Contact Us") ?></span></a>
			</li>
		</ul>
	</div>
</div>
