<ul class='dl-menu'><li class=""><a class="" title="<?php echo $this->__("Bikes") ?>" target="_self" href="#"><span class="title"><?php echo $this->__("Bikes") ?></span></a><ul class="dl-submenu"><li class=""><a class="" title="<?php echo $this->__("Road") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>buy-road-bikes/"><span><?php echo $this->__("Road") ?></span></a><ul class='dl-submenu'><li class='autosub-item '><a title="<?php echo $this->__("Racing Bikes") ?>" href="<?php echo $this->getMCPUrl()?>buy-road-bikes/racing/"><?php echo $this->__("Racing Bikes") ?></a>
</li><li class='autosub-item '><a title="<?php echo $this->__("Cyclocross Bikes") ?>" href="<?php echo $this->getMCPUrl()?>buy-road-bikes/cyclocross/"><?php echo $this->__("Cyclocross Bikes") ?></a>
</li><li class='autosub-item '><a title="<?php echo $this->__("Endurance Bikes") ?>" href="<?php echo $this->getMCPUrl()?>buy-road-bikes/endurance/"><?php echo $this->__("Endurance Bikes") ?></a>
</li><li class='autosub-item '><a title="<?php echo $this->__("Sport Bikes") ?>" href="<?php echo $this->getMCPUrl()?>buy-road-bikes/sport/"><?php echo $this->__("Sport Bikes") ?></a>
</li><li class='autosub-item '><a title="<?php echo $this->__("Triathlon Bikes") ?>" href="<?php echo $this->getMCPUrl()?>buy-road-bikes/triathlon/"><?php echo $this->__("Triathlon Bikes") ?></a>
</li><li class='autosub-item '><a title="<?php echo $this->__("Touring Bikes") ?>" href="<?php echo $this->getMCPUrl()?>buy-road-bikes/touring/"><?php echo $this->__("Touring Bikes") ?></a>
</li></ul>

</li><li class=""><a class="" title="<?php echo $this->__("Mountain") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>buy-cheap-mountain-bikes/"><span><?php echo $this->__("Mountain") ?></span></a><ul class='dl-submenu'><li class='autosub-item '><a title="<?php echo $this->__("Dirt Jump Bikes") ?>" href="<?php echo $this->getMCPUrl()?>buy-cheap-mountain-bikes/dirt-jump/"><?php echo $this->__("Dirt Jump Bikes") ?></a>
</li><li class='autosub-item '><a title="<?php echo $this->__("Downhill Bikes") ?>" href="<?php echo $this->getMCPUrl()?>buy-cheap-mountain-bikes/downhill/"><?php echo $this->__("Downhill Bikes") ?></a>
</li><li class='autosub-item '><a title="<?php echo $this->__("Dual Suspension Bikes") ?>" href="<?php echo $this->getMCPUrl()?>buy-cheap-mountain-bikes/dual-suspension/"><?php echo $this->__("Dual Suspension Bikes") ?></a>
</li><li class='autosub-item '><a title="<?php echo $this->__("Recreational Bikes") ?>" href="<?php echo $this->getMCPUrl()?>buy-cheap-mountain-bikes/recreational/"><?php echo $this->__("Recreational Bikes") ?></a>
</li><li class='autosub-item '><a title="<?php echo $this->__("Trail Hardtail Bikes") ?>" href="<?php echo $this->getMCPUrl()?>buy-cheap-mountain-bikes/trail-hardtail/"><?php echo $this->__("Trail Hardtail Bikes") ?></a>
</li><li class='autosub-item '><a title="<?php echo $this->__("XC Hardtail Bikes") ?>" href="<?php echo $this->getMCPUrl()?>buy-cheap-mountain-bikes/xc-hardtail/"><?php echo $this->__("XC Hardtail Bikes") ?></a>
</li><li class='autosub-item '><a title="<?php echo $this->__("Fat Bikes") ?>" href="<?php echo $this->getMCPUrl()?>buy-cheap-mountain-bikes/fat/"><?php echo $this->__("Fat Bikes") ?></a>
</li></ul>

</li><li class=""><a class="" title="<?php echo $this->__("Commuter") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>commuter/"><span><?php echo $this->__("Commuter") ?></span></a><ul class='dl-submenu'><li class='autosub-item '><a title="<?php echo $this->__("Fixie Bikes") ?>" href="<?php echo $this->getMCPUrl()?>commuter/fixie-single-speed/"><?php echo $this->__("Fixie Bikes") ?></a>
</li><li class='autosub-item '><a title="<?php echo $this->__("Flat Bar Road Bikes") ?>" href="<?php echo $this->getMCPUrl()?>commuter/flat-bar-road/"><?php echo $this->__("Flat Bar Road Bikes") ?></a>
</li><li class='autosub-item '><a title="<?php echo $this->__("Urban Bikes") ?>" href="<?php echo $this->getMCPUrl()?>commuter/urban/"><?php echo $this->__("Urban Bikes") ?></a>
</li></ul>

</li><li/><a class="" title="<?php echo $this->__("Hybrid") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>hybrid/"><span><?php echo $this->__("Hybrid") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Electric") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>electric-bike/"><span><?php echo $this->__("Electric") ?></span></a>
</li><li class=""><a class="" title="<?php echo $this->__("Kids") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>kids/"><span><?php echo $this->__("Kids") ?></span></a><ul class='dl-submenu'><li class='autosub-item '><a title="<?php echo $this->__("Single Speed Bikes") ?>" href="<?php echo $this->getMCPUrl()?>kids/single-speed/"><?php echo $this->__("Single Speed Bikes") ?></a>
</li><li class='autosub-item '><a title="<?php echo $this->__("Geared Bikes") ?>" href="<?php echo $this->getMCPUrl()?>kids/geared/"><?php echo $this->__("Geared Bikes") ?></a>
</li><li class='autosub-item '><a title="<?php echo $this->__("Balance Bikes") ?>" href="<?php echo $this->getMCPUrl()?>kids/balance/"><?php echo $this->__("Balance Bikes") ?></a>
</li><li class='autosub-item '><a title="<?php echo $this->__("Tricycles") ?>" href="<?php echo $this->getMCPUrl()?>kids/tricycles/"><?php echo $this->__("Tricycles") ?></a>
</li><li class='autosub-item '><a title="<?php echo $this->__("Scooters") ?>" href="<?php echo $this->getMCPUrl()?>kids/scooters/"><?php echo $this->__("Scooters") ?></a>
</li><li class='autosub-item '><a title="<?php echo $this->__("Tag Along Bikes") ?>" href="<?php echo $this->getMCPUrl()?>kids/tag-along/"><?php echo $this->__("Tag Along Bikes") ?></a>
</li></ul>

</li><li/><a class="" title="<?php echo $this->__("Retro / Vintage") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>vintage-retro-bikes/"><span><?php echo $this->__("Retro / Vintage") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Cruiser") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>cruiser/"><span><?php echo $this->__("Cruiser") ?></span></a>
</li><li class=""><a class="" title="<?php echo $this->__("BMX") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bmx/"><span><?php echo $this->__("BMX") ?></span></a><ul class='dl-submenu'><li class='autosub-item '><a title="<?php echo $this->__("Street BMX Bikes") ?>" href="<?php echo $this->getMCPUrl()?>bmx/street/"><?php echo $this->__("Street BMX Bikes") ?></a>
</li><li class='autosub-item '><a title="<?php echo $this->__("Cruiser BMX Bikes") ?>" href="<?php echo $this->getMCPUrl()?>bmx/cruiser/"><?php echo $this->__("Cruiser BMX Bikes") ?></a>
</li><li class='autosub-item '><a title="<?php echo $this->__("Retro BMX Bikes") ?>" href="<?php echo $this->getMCPUrl()?>bmx/retro/"><?php echo $this->__("Retro BMX Bikes") ?></a>
</li></ul>

</li><li/><a class="" title="<?php echo $this->__("Folding") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>folding/"><span><?php echo $this->__("Folding") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Trikes") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>trikes/"><span><?php echo $this->__("Trikes") ?></span></a>
</li></ul>

</li><li class=""><a class="" title="<?php echo $this->__("Accessories") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/"><span><?php echo $this->__("Bikes Accessories") ?></span></a><ul class="dl-submenu"><li/><a class="" title="<?php echo $this->__("Baby Seats") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/child-seats/"><span><?php echo $this->__("Baby Seats") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Grips") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/grips/"><span><?php echo $this->__("Grips") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Mudguards") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/mudguards/"><span><?php echo $this->__("Mudguards") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Backpacks") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/backpacks/"><span><?php echo $this->__("Backpacks") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Handlebar Tape") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/handlebar-tape/"><span><?php echo $this->__("Handlebar Tape") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Nutrition") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/nutrition/"><span><?php echo $this->__("Nutrition") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Bags &amp; Panniers") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/bags/"><span><?php echo $this->__("Bags &amp; Panniers") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Helmets") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/helmets/"><span><?php echo $this->__("Helmets") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Pegs") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/bmx-pegs/"><span><?php echo $this->__("Pegs") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Bar Ends") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/bar-ends/"><span><?php echo $this->__("Bar Ends") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Home Trainers") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/home-trainers/"><span><?php echo $this->__("Home Trainers") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Pumps") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/pumps/"><span><?php echo $this->__("Pumps") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Baskets") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/baskets/"><span><?php echo $this->__("Baskets") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Kickstands") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/kickstands/"><span><?php echo $this->__("Kickstands") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Racks") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/carry-racks/"><span><?php echo $this->__("Racks") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Bells &amp; Horns") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/bells-horns/"><span><?php echo $this->__("Bells &amp; Horns") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Kids Bike Accessories") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/kids-bike-accessories/"><span><?php echo $this->__("Kids Bike Accessories") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Storage &amp; Stands") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/storage-and-stands/"><span><?php echo $this->__("Storage &amp; Stands") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Bike Covers") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/covers/"><span><?php echo $this->__("Bike Covers") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Lights") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/lights/"><span><?php echo $this->__("Lights") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Sunscreen") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/sunscreen/"><span><?php echo $this->__("Sunscreen") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Bottle Cages") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/bottle-cages/"><span><?php echo $this->__("Bottle Cages") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Locks") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/locks/"><span><?php echo $this->__("Locks") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Tools") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/tools/"><span><?php echo $this->__("Tools") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Car Racks") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/carriers-racks/"><span><?php echo $this->__("Car Racks") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Lubrication") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/lubrication-cleaning/"><span><?php echo $this->__("Lubrication") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Trailers") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/trailers/"><span><?php echo $this->__("Trailers") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Chamois Cream") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/chamois-cream/"><span><?php echo $this->__("Chamois Cream") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Maps &amp; Books") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/books/"><span><?php echo $this->__("Maps &amp; Books") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Tyre Sealant") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/tyre-sealant/"><span><?php echo $this->__("Tyre Sealant") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Computers") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/computers/"><span><?php echo $this->__("Computers") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Mirrors") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/mirrors/"><span><?php echo $this->__("Mirrors") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Water Bottles") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/water-bottles/"><span><?php echo $this->__("Water Bottles") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Gift Vouchers") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/gift-vouchers/"><span><?php echo $this->__("Gift Vouchers") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Mobile Accessories") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-accessories/mobile-phone-accessories/"><span><?php echo $this->__("Mobile Accessories") ?></span></a>
</li></ul>

</li><li class=""><a class="" title="<?php echo $this->__("Parts") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>parts/"><span><?php echo $this->__("Parts") ?></span></a><ul class="dl-submenu"><li/><a class="" title="<?php echo $this->__("Axles &amp; Skewers") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>parts/axles-skewers/"><span><?php echo $this->__("Axles &amp; Skewers") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Forks") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>parts/forks/"><span><?php echo $this->__("Forks") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Seat Posts") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>parts/seat-posts/"><span><?php echo $this->__("Seat Posts") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Batteries") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>parts/light-batteries/"><span><?php echo $this->__("Batteries") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Freewheels") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>parts/freewheels-sprockets/"><span><?php echo $this->__("Freewheels") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Shifters") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>parts/shifters/"><span><?php echo $this->__("Shifters") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Bottom Brackets") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>parts/bottom-brackets/"><span><?php echo $this->__("Bottom Brackets") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Handlebars") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>parts/handlebars/"><span><?php echo $this->__("Handlebars") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Stems") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>parts/stems/"><span><?php echo $this->__("Stems") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Brakes") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>parts/brakes/"><span><?php echo $this->__("Brakes") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Headsets") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>parts/headsets/"><span><?php echo $this->__("Headsets") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Tubes") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>parts/tubes/"><span><?php echo $this->__("Tubes") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Chains") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>parts/chains/"><span><?php echo $this->__("Chains") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Pedals &amp; Cleats") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>parts/pedals/"><span><?php echo $this->__("Pedals &amp; Cleats") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Tyres") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>parts/tyres/"><span><?php echo $this->__("Tyres") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Crank Sets") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>parts/crank-sets/"><span><?php echo $this->__("Crank Sets") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Saddles") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>parts/seats/"><span><?php echo $this->__("Saddles") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Wheels") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>parts/wheels/"><span><?php echo $this->__("Wheels") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Derailleurs") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>parts/derailleurs/"><span><?php echo $this->__("Derailleurs") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Derailleur Hangers") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-derailleur-hangers"><span><?php echo $this->__("Derailleur Hangers") ?></span></a>
</li></ul>

</li><li class=""><a class="" title="<?php echo $this->__("Clothing") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>clothing/"><span><?php echo $this->__("Clothing") ?></span></a><ul class="dl-submenu"><li/><a class="" title="<?php echo $this->__("Arm Warmers") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>clothing/arm-warmers/"><span><?php echo $this->__("Arm Warmers") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Jerseys") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>clothing/jerseys/"><span><?php echo $this->__("Jerseys") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Shoes") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>clothing/shoes/"><span><?php echo $this->__("Shoes") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Bib Knicks") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>clothing/bib-shorts/"><span><?php echo $this->__("Bib Knicks") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Knee Warmers") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>clothing/knee-warmers/"><span><?php echo $this->__("Knee Warmers") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Shoe Covers") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>clothing/shoe-covers/"><span><?php echo $this->__("Shoe Covers") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Body Armour") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>clothing/body-armour-crash-pads/"><span><?php echo $this->__("Body Armour") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Knicks &amp; Shorts") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>clothing/shorts-knicks/"><span><?php echo $this->__("Knicks &amp; Shorts") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Socks") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>clothing/socks/"><span><?php echo $this->__("Socks") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Gloves") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>clothing/gloves/"><span><?php echo $this->__("Gloves") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Leg Warmers") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>clothing/leg-warmers/"><span><?php echo $this->__("Leg Warmers") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Sunglasses") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>clothing/sunglasses/"><span><?php echo $this->__("Sunglasses") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Head &amp; Ear Warmers") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>clothing/head-ear-warmers/"><span><?php echo $this->__("Head &amp; Ear Warmers") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Safety Gear") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>clothing/safety-gear/"><span><?php echo $this->__("Safety Gear") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Tights") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>clothing/tights/"><span><?php echo $this->__("Tights") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Jackets") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>clothing/jackets/"><span><?php echo $this->__("Jackets") ?></span></a>
</li></ul>

</li><li class=""><a class="" title="<?php echo $this->__("Repairs") ?>" target="_self" href="#"><span class="title"><?php echo $this->__("Repairs") ?></span></a><ul class="dl-submenu"><li/><a class="" title="<?php echo $this->__("In Store Repairs") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>bike-servicing/"><span><?php echo $this->__("In Store Repairs") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Mobile Mechanic Service") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>mbc-mobile-mechanic-service/"><span><?php echo $this->__("Mobile Mechanic Service") ?></span></a>
</li></ul>

</li><li/><a class="" title="<?php echo $this->__("Brands") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>brands/"><span><?php echo $this->__("Brands") ?></span></a>
</li><li/><a class="" title="<?php echo $this->__("Contact Us") ?>" target="_self" href="<?php echo $this->getMCPBaseUrl() ?>contacts/"><span><?php echo $this->__("Contact Us") ?></span></a>
</li></ul>
